- src/controllers/imagem_controller/ImagemController.js
- src/executores/imagem_executor/DownloadImagensBaseInternaExecutor.js
- src/executores/usuario_executor/ObterUsuarioExecutor.js
Related with https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/30
Due Node.js async, the browser is creating a empty file.
> Create ZIP file per request

- docs/examples/501-get-download.sh
- src/executores/imagem_executor/DownloadImagensBaseInternaExecutor.js
CSV file
```
image_id,image_filename,image_doi,cell_id,characteristics,nucleus_x,nucleus_y
1,example0001.jpg,,1,1,274,321
1,example0001.jpg,,2,2,263,97
```
JSON file
```
[
{
"image_id": 1,
"image_doi": "",
"image_name": "example0001.jpg",
"classifications": [
{
"cell_id": 1,
"characterisitics": 1,
"nucleus_x": 274,
"nucleus_y": 321
},
{
"cell_id": 2,
"characterisitics": 2,
"nucleus_x": 263,
"nucleus_y": 97
}
]
},
{
"image_id": 2,
"image_doi": "",
"image_name": "example0002.jpg",
"classifications": []
},
{
"image_id": 3,
"image_doi": "",
"image_name": "example0003.jpg",
"classifications": []
}
]
```
> Add CSV and JSON file for classifications

- docs/debugging.rst
- package-lock.json
- package.json
- src/controllers/imagem_controller/ImagemController.js
- src/executores/imagem_executor/DownloadImagensBaseInternaExecutor.js
- src/server.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/44.
> Use debug package

- src/executores/imagem_executor/CadastrarImagemExecutor.js
- src/executores/imagem_executor/CadastrarSegmentacaoCelulaExecutor.js
- src/executores/usuario_executor/CadastrarAdministradorExecutor.js
- src/executores/usuario_executor/CadastrarAnalistaExecutor.js
- src/executores/usuario_executor/CadastrarCitopatologistaExecutor.js
- src/executores/usuario_executor/CadastrarUsuarioBaseExcutor.js
- src/executores/usuario_executor/CadastrarVisitanteExecutor.js
- src/executores/usuario_executor/ObterUsuarioExecutor.js
- src/executores/usuario_executor/TornarCitopatologistaExecutor.js
close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/45
> changing executers errors

- src/migrations/20200501125636-doi.js
- src/models/ImagemModel.js
- src/repositorios/imagem_repositorio.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/79
> Add DOI field to image

- docs/examples/410-get-imagens-classificacao-celula.sh
- docs/rest_api/image.rst
- src/executores/imagem_executor/ListarClassificacaoCelulaExecutor.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/62
> WIP: Fix return of /api/v1/imagens/{image_id}/classificacao-celula/{user_id}

- .travis.yml
- jest.config.js
- package-lock.json
- package.json
- src/__tests__/system.js
- src/app.js
- src/server.js
Uses supertests and jest.
Based on https://www.albertgao.xyz/2017/05/24/how-to-test-expressjs-with-jest-and-supertest/
> Add example of test

- .eslintrc.json
- config/test.js
- package-lock.json
- package.json
- src/__tests__/system.js
- src/fixtures/analyst.js
- src/fixtures/user.js
- src/repositorios/user.test.js
> Add test for Data Access Object

- .travis.yml
- config/test.js
- config/travis.js
- jest.config.js
- package.json
- src/__tests__/setup.js
- src/__tests__/teardown.js
- src/fixtures/admin.js
- src/repositorios/user.test.js
Because sequelize-mock can't provide the features that we need.
> Avoid mock for test

- src/__tests__/image.js
- src/__tests__/system.js
- src/executores/sistema/ObterStatusSistemaExecutor.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/106
> Test rotasIndex.js

- src/__tests__/image.js
- src/__tests__/setup.js
- src/fixtures/classification.js
Related to https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/108
> Test rotasImagem.js for anonymous user

- src/__tests__/image.js
- src/executores/imagem_executor/CadastrarImagemExecutor.js
- src/migrations/20200629113156-image-injury.js
- src/repositorios/imagem_repositorio.js
So that user doesn't have to provide the injury of the image **since** the injury is calculated when the user classify the cells.
> Force new image to have id_lesao equal to 1

- src/__tests__/image.js
- src/__tests__/injury.js
- src/__tests__/user.js
- src/controllers/imagem_controller/ImagemController.js
- src/controllers/sistema/SistemaController.js
- src/controllers/usuario_controller/UsuarioController.js
- src/executores/imagem_executor/DownloadBaseExecutor.js
- src/executores/imagem_executor/ListarClassificacaoCelulaExecutor.js
- src/executores/imagem_executor/ListarSegmentacaoCelulaExecutor.js
- src/executores/usuario_executor/FazerLogOffExecutor.js
- src/executores/usuario_executor/ListarUsuariosExecutor.js
- src/fixtures/cell.js
- src/fixtures/classification.js
- src/fixtures/cytoplasm.js
- src/repositorios/imagem_repositorio.js
@costascaio please note that I re-structure the test suit. It is organise now as
```
describe(
"GET /route/to/test",
() => {
test(
"anonymous",
() => {
return request(app)
.get("/route/to/test")
.then(
response => {
expect(response.statusCode).toBe(200);
}
);
}
);
test(
"charles",
() => {
return request(app)
.get("/route/to/test")
.then(
response => {
expect(response.statusCode).toBe(200);
}
);
}
);
test(
"admin",
() => {
return request(app)
.get("/route/to/test")
.then(
response => {
expect(response.statusCode).toBe(200);
}
);
}
);
}
);
```
> Improve test suit structure

- src/fixtures/user.json
- src/migrations/20200722171203-bool.js
- src/models/ClassificacaoCelulaModel.js
- src/models/ImagemModel.js
- src/models/SegmentacaoCitoplasmaModel.js
- src/models/SegmentacaoNucleoModel.js
Related to https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/5
> Use of datatype Sequelize.BOOLEAN

- src/__tests__/image.js
- src/__tests__/injury.js
- src/__tests__/system.js
- src/__tests__/user.js
- src/controllers/sistema/SistemaController.js
- src/executores/usuario_executor/DeleteUserService.js
- src/executores/usuario_executor/MakeAdminService.js
- src/executores/usuario_executor/ObterUsuarioExecutor.js
- src/executores/usuario_executor/RemoveAdminService.js
- src/utils/validador_de_sessao.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/24
> Add API endpoint to promote user to admin

- src/controllers/injuries.js
- src/executores/injuries/get_injury.js
- src/rotas/rotasLesoes.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/175
> Implement GET /api/v1/lesoes/:id_lesoes(\d+)

- src/controllers/injuries.js
- src/executores/injuries/put_inury.js
- src/repositorios/imagem_repositorio.js
- src/rotas/rotasLesoes.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/176
> Implement PUT /api/v1/lesoes/:id_lesoes(\d+)

- src/controllers/imagem_controller/ImagemController.js
- src/executores/imagem_executor/delete_image.js
- src/repositorios/imagem_repositorio.js
- src/rotas/rotasImagem.js
Close https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/169
> Implement DELETE /api/v1/imagens/id_imagem

- reference/cric.v2.yaml
Initialize method GET and POST.
> Start to document collection endpoints

- src/executores/imagem_executor/CadastrarClassificacaoCelulaExecutor.js
Fix https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/187
> Fix internal server error 500

- src/controllers/imagem_controller/ImagemController.js
- src/executores/imagem_executor/CadastrarClassificacaoCelulaExecutor.js
- src/executores/imagem_executor/CadastrarSegmentacaoCelulaExecutor.js
- src/executores/imagem_executor/delete_image.js
- src/executores/injuries/put_injury.js
> Add a new image segmentation fixed

- src/executores/imagem_executor/AtualizarClassificacaoExecutor.js
> Update classification fixed

- src/controllers/imagem_controller/ImagemController.js
- src/executores/imagem_executor/CadastrarClassificacaoCelulaExecutor.js
- src/executores/imagem_executor/DownloadBaseExecutor.js
- src/executores/imagem_executor/ExcluirClassificacaoExecutor.js
- src/migrations/20191104235127-descricao.js
- src/rotas/rotasImagem.js
- src/utils/image.js
Resolve #200
Resolve #198
Resolve #197
> Finalizing playground
